### ISSUE TITLE
Problems installing sni2torproxy

### ISSUE THREAD

**Issue by dashohoxha** [Own-Mailbox/proxy#3]
When running configuration script `ds inject cfg/sni2torproxy.sh` (this one: https://github.com/Own-Mailbox/proxy/blob/master/scripts/cfg/sni2torproxy.sh), I get compilation errors like these:
```
/opt/Own-Mailbox/sni2tor-proxy/src/database.c:14: undefined reference to `mysql_init'
/opt/Own-Mailbox/sni2tor-proxy/src/database.c:16: undefined reference to `mysql_real_connect'
/opt/Own-Mailbox/sni2tor-proxy/src/database.c:18: undefined reference to `mysql_error'
sni2torproxy-database.o: In function `request_corresponding_service':
/opt/Own-Mailbox/sni2tor-proxy/src/database.c:41: undefined reference to `mysql_query'
/opt/Own-Mailbox/sni2tor-proxy/src/database.c:46: undefined reference to `mysql_use_result'
/opt/Own-Mailbox/sni2tor-proxy/src/database.c:48: undefined reference to `mysql_fetch_row'
/opt/Own-Mailbox/sni2tor-proxy/src/database.c:54: undefined reference to `mysql_free_result'
/opt/Own-Mailbox/sni2tor-proxy/src/database.c:42: undefined reference to `mysql_error'
sni2torproxy-database.o: In function `close_database_sin2tor':
/opt/Own-Mailbox/sni2tor-proxy/src/database.c:61: undefined reference to `mysql_close'
collect2: error: ld returned 1 exit status
Makefile:388: recipe for target 'sni2torproxy' failed
make[1]: *** [sni2torproxy] Error 1
```
What can be missing?
I have used **mariadb-server** instead of **mysql-server** (see: https://github.com/Own-Mailbox/proxy/blob/master/Dockerfile#L20-L26), but they are supposed to be binary compatible, so that nothing else needs to be changed.

**Comment by pparent76** [comment]
Hum you need default-libmysqlclient-dev or something like that.

**Comment by dashohoxha** [comment]
The code of sni2torproxy is clone from this repository: https://github.com/Own-Mailbox/sni2tor-proxy
which in turn is a fork of this repository: https://github.com/pparent76/sni2tor-proxy
In the last repository I see this message: "This branch is 19 commits ahead, 53 commits behind dlundquist:master."
Is it a problem if I merge all the latest changes from https://github.com/dlundquist/sniproxy?
Maybe it will not solve this bug, but probably it may be a good thing to do.

**Comment by dashohoxha** [comment]
I tried to replace mariadb by mysql, but the compilation failed again. Maybe there is something that needs to be fixed on the Makefile or on the code.

**Comment by pparent76** [comment]
It works for me on Debian jessie, with vagrant.
